CREATE TABLE IF NOT EXISTS roles(
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (45)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR (45) NOT NULL UNIQUE,
    email VARCHAR (45) NOT NULL UNIQUE,
    password VARCHAR (45) NOT NULL
);


CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL ,
    role_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL ,
    firstname VARCHAR (45) NOT NULL ,
    lastname VARCHAR (45) NOT NULL ,
    created_timestamp TIMESTAMP DEFAULT NOW(),
    updated_timestamp TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (45) NOT NULL ,
    external_id BIGINT
);

CREATE TABLE IF NOT EXISTS movie_genres(
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS movies(
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    adult BOOLEAN DEFAULT FALSE ,
    backdrop_path VARCHAR (256) ,
    genre INTEGER  NOT NULL,
    language VARCHAR (45) ,
    title TEXT ,
    overview TEXT
);

CREATE TABLE IF NOT EXISTS user_movie(
    id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL ,
    movie_id BIGINT NOT NULL  ,
    status INT NOT NULL DEFAULT 1,
    description TEXT,
    rating INTEGER ,
    created_timestamp TIMESTAMP DEFAULT NOW(),
    updated_timestamp TIMESTAMP DEFAULT NOW()
    );

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE user_roles ADD CONSTRAINT fk_user_roles_role
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE profiles ADD CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE movie_genres ADD CONSTRAINT fk_movie_genres_movie
    FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE movie_genres ADD CONSTRAINT fk_movie_genres_genre
    FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE user_movie ADD CONSTRAINT fk_user_movie_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE user_movie ADD CONSTRAINT fk_user_movie_movie
    FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE ON UPDATE CASCADE;